-- ============================================
-- Idea Communicator Database Initialization
-- ============================================
-- This script runs when the PostgreSQL container starts for the first time

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";  -- For text search

-- ============================================
-- Create basic schema (will be expanded in later phases)
-- ============================================

-- Set timezone
SET timezone = 'UTC';

-- Create audit log function for GDPR compliance
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ============================================
-- Initial tables (basic structure for Fas 0/1)
-- ============================================

-- Users table (will be created by TypeORM in Fas 1)
-- Groups table (will be created by TypeORM in Fas 2)
-- Messages table (will be created by TypeORM in Fas 2)
-- Calls table (will be created by TypeORM in Fas 3)
-- Recordings table (will be created by TypeORM in Fas 4)
-- Transcriptions table (will be created by TypeORM in Fas 5)

-- Placeholder comment: Tables will be auto-generated by TypeORM
-- This init script ensures extensions are installed

-- ============================================
-- Create indexes and constraints
-- ============================================
-- Will be added in respective phases

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE ideacomm TO ideacomm_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ideacomm_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ideacomm_user;

-- Log successful initialization
DO $$
BEGIN
    RAISE NOTICE 'Database initialized successfully';
    RAISE NOTICE 'Extensions enabled: uuid-ossp, pg_trgm';
    RAISE NOTICE 'Ready for TypeORM auto-migration';
END $$;
